def help_msg(name=None):

	return '''
	========================OVERVIEW=========================
	Utility for building input for FlexPepDock refinement:
	Will take a .fasta file with a list of epitopes and
	an HLA allele of interest and build input files for a
	FlexPepDock refinement run, by creating threaded MHC/
	peptide structures from a local database (created by
	calling MHCdatabase().build() from HLA_db.py). Produces
	an input file, options file, and slurm file for use
	on clusters that use SLURM for job scheduling. 

	Also used for querying IEDB database and building 
	structural models from resultant query:
	Takes in an HLA or MHC-I allele name (such as "A*02:01").
	Searches the IEDB for all epitopes with experimentally
	determined binding affinity data for that allele. 
	Sorts, removes duplicates, and returns (1)
	a fasta file without flagged values (those that passed
	the tests in the data validation stage) and (2) a 
	tab-delimited text file with epitope IDs, pubmed IDs,
	and quantitative binding values. These should be reviewed
	manually, and bad values deleted after literature review.
	The curated file can then be passed back to this utility
	with the original output fasta file, and the two will be
	combined before being shunted down the pipeline as
	described.

	==========================PYTHON DEPENDENCIES==========================
	BioPython
    pandas
    numpy
    requests
    formats.py (custom class in same folder as IEDBTestPipeline.py)
    HLA_db.py (custom class in same folder as IEDBTestPipeline.py)
    
    ===========================PIPELINE SUMMARY============================

    |==>Retrieve epitope list from IEDB. [Optional step 1]
    |    
    |   python IEDBTestPipeline.py --IEDBquery A*02:01
    |
    |   >Epitopes processed: 4500000   Epitopes found: 13342     
    |   >Flagged epitope data located in flagged_HLA-A*02:01_IEDB_data.csv
    |   >Filtered IEDB data written to cleaned_HLA-A*02:01_IEDB_data.csv
    |   >Epitope sequences written to HLA-A*02:01.fasta
    |
    |==>Build fasta file from curated data. Include NCAA
    |   if applicable. NOTE: Can pass a custom .fasta file followed
    |   by a 0 if step 1 was omitted.
    |
    |   python IEDBTestPipeline.py --buildFasta HLA-A*02:01.fasta \\
    |                              flagged_HLA-A*02:01_IEDB_data.csv
    |
    |   OR
    |
    |   python IEDBTestPipeline.py --buildFasta custom.fasta 0
    |
    |   >Creates one folder for each sequence in the .fasta file, named
    |    after the sequence <record_name>
    |   >Folder contents:
    |     <record_name>_input.pdb
    |                          : Prepacked input PDB for FlexPepDock
    |                            Refinement
    |     <record_name>.fasta  : fasta file with peptide sequence,
    |                            modified to include NCAA if applicable
    |     <record_name>.slurm  : SLURM file with options specified by
    |                            user if --slurm argument passed
    |     <record_name>.options: .options file for Rosetta FlexPepDock
    |                            with additional values specified by
    |                            user if --options argument passed
    |     flexpepdock_input_<record_name>.xml
    |                          : RosettaScripts protocol for building
    |                            input for FlexPepDock Refinement
    |                            production run
    |     tmp_receptor.pdb     : Model of MHC-1/HLA receptor
    |                            (specified by user with --receptor
    |                            or generated by AlphaFold2)
    |     score.sc             : Scorefile for input PDB generated by
    |                            FlexPepDock prepack
    |
    |==>Postprocessing (scorefile generation)
    |
    |   python IEDBTestPipeline.py --post build <path/to/silent/files/>
    |
    |   >Produces sorted_scores.sc
    |
    |==>Postprocessing (generate statistics for peptide binding affinity 
    |   from IEDB data)
    |
    |   python IEDBTestPipeline.py --post affinity\\ 
    |                              cleaned_HLA-A*02:01_IEDB_data.csv\\
    |                              sorted_scores.sc\\
    |                              flagged_HLA-A*02:01_IEDB_data.csv
    |
    |  >Produces several files with descriptive statistics for
    |   scorefile energy terms as binding affinity predictors


    ===========================CLUSTER USAGE============================

    |==>Run the pipeline in SLURM setup mode to generate batch files:
    |   python IEDBTestPipeline.py --slurm_setup --buildFasta /path/to/allele_folders
    |
    |   > Generates batch_list.txt containing all batch directories for processing.
    |
    |==> After generating the batch list, submit the SLURM job array to process the batches:
    |   sbatch submit_slurm_job.sh
	|
    ===========================END OF HELP==============================
	'''

##==process_peplist==#
# A wrapper that calls get_peplist if the user wants to retrive data for multiple alleles
# def process_peplist(allelelist):

def flatten_columns(df):
	if isinstance(df.columns, pd.MultiIndex):
		df.columns = [' '.join(col).strip() for col in df.columns]
	return df

def standardize_columns(df):
	df.columns = (df.columns.str.strip().str.replace(' ', '_').str.replace('/', '-').str.lower())
	return df

def rename_columns(df):
	rename_map = {
        "mhc_restriction_name": "mhc_restriction_name",
        "epitope_source_molecule": "parent_protein_accession",
        "epitope_name": "description",
        "reference_pmid": "pubmed_id",
        "assay_quantitative_measurement": "quantitative_measurement"}

	df.rename(columns=rename_map, inplace=True)
	return df

def clean_peplist(peplist,prefix=""):
	peplist["Flag"] = False # Set a flag value here in case we need to do a manual review

	# Filter data: keep only relevant columns and only rows that contain binding affinity data
	# peplist=peplist[['Epitope_ID','PubMed_ID', 'Description', 'Parent_Protein', 'Parent_Protein_Accession', 'Method-Technique', 'Assay_Group', 'Quantitative_measurement', 'PDB_ID', 'Allele_Name']]

	# Filter data: keep only relevant rows with both Quantitative_Measurement and Assay_Units
	peplist = peplist.dropna(subset=["Quantitative_Measurement", "Assay_Units"])

	# Standardize 'Assay_Response' values
	peplist.loc[:, "Assay_Response_Standardized"] = peplist["Assay_Response_Measured"].replace({"dissociation constant KD (~EC50)": "dissociation constant (KD)", "dissociation constant KD": "dissociation constant (KD)", "dissociation constant KD (~IC50)": "dissociation constant (KD)"})

	# Filter out entries that don't match the valid responses criteria
	valid_responses = ["dissociation constant (KD)", "half maximal inhibitory concentration (IC50)"]
	peplist = peplist[peplist["Assay_Response_Standardized"].isin(valid_responses)].copy()

	start_len=len(peplist)
	print(f'{start_len} starting records')

	if "Epitope_ID" not in peplist.columns:
		raise KeyError("Missing expected column 'Epitope ID' after renaming. Check source or renaming logic.")

	enames = peplist["Epitope_ID"].unique()
	print(f'{len(enames)} unique epitope IDs')
	print("Filtering duplicate epitopes...")

	filtered_count=0
	for e in peplist["Epitope_ID"].unique():
		filtered_count += 1
		if filtered_count % 1000 == 0 or filtered_count == len(peplist["Epitope_ID"].unique()):
			print(f"Filtered {filtered_count:<10} of {len(peplist['Epitope_ID'].unique()):<10}", end="\r")

		for assay_type in ["dissociation constant (KD)", "half maximal inhibitory concentration (IC50)"]:
			tmp = peplist[(peplist["Epitope_ID"] == e) & (peplist["Assay_Response_Standardized"] == assay_type)].copy()

			if len(tmp) == 2:
				pubmed_nan = tmp["PubMed_ID"].isna()
				values = tmp["Quantitative_Measurement"].tolist()
				value_diff = abs(values[0] - values[1])

				if pubmed_nan.any() and not pubmed_nan.all():
					# Prefer the one with a PubMed ID
					to_drop = tmp.index[pubmed_nan][0]
					peplist.drop(to_drop, inplace=True)

				elif pubmed_nan.all() and value_diff > 10:
					# Both missing PubMed, and values far apart → drop both
					peplist.drop(tmp.index, inplace=True)

				elif pubmed_nan.all() and value_diff <= 10:
					# Both missing PubMed ID and values are similar → keep one (e.g., the first)
					peplist.drop(tmp.index[1], inplace=True)

				elif tmp["PubMed_ID"].notna().all():
					if value_diff < 10:
						# Both have PubMed, values similar → drop one (arbitrary)
						peplist.drop(tmp.index[0], inplace=True)
					else:
						# Both have PubMed, values conflict → flag
						peplist.loc[tmp.index, "Flag"] = True
				else:
					# All other ambiguous cases → flag
					peplist.loc[tmp.index, "Flag"] = True

			elif len(tmp) > 2:
				pubmed_nan = tmp["PubMed_ID"].isna()
				values = tmp["Quantitative_Measurement"].tolist()

				# Remove entries with missing PubMed IDs first
				drop_ids = tmp[pubmed_nan].index
				peplist.drop(drop_ids, inplace=True)
				tmp = tmp.drop(drop_ids)

				# If there are still entries to process, handle them:
				if len(tmp) > 2:
					# Check if values are within 10 of each other
					value_diff_matrix = np.abs(np.subtract.outer(values, values))
					value_diff_matrix = np.tril(value_diff_matrix, -1)  # Ignore diagonal, we don't compare to self

					if (value_diff_matrix <= 10).sum(axis=1).max() == len(values) - 1:
						# All values are within 10, keep one of the entries (e.g., the first one)
						peplist.drop(tmp.index[1:], inplace=True)
					else:
						# If we have a case where values differ significantly, keep the one closest to the median
						median_value = np.median(values)
						closest_to_median_idx = np.argmin(np.abs(np.array(values) - median_value))
						peplist.drop(tmp.index.difference([tmp.index[closest_to_median_idx]]), inplace=True)

			# Handle cases where we outliers
			elif len(tmp) > 2 and tmp["Quantitative_Measurement"].nunique() > 1:
				# Remove the outlier then take the median of the rest
				values = tmp["Quantitative_Measurement"].tolist()
				outlier_value = max(values)
				tmp_cleaned = tmp[tmp["Quantitative_Measurement"] != outlier_value]
				median_value = np.median(tmp_cleaned["Quantitative_Measurement"])
				# Add back the median value entry
				tmp_cleaned["Quantitative_Measurement"] = median_value
				peplist.loc[tmp_cleaned.index, "Quantitative_Measurement"] = median_value

			# Handle edge cases where multiple values are very close
			elif len(tmp) > 2:
				# If multiple values are close, take the median and drop the rest
				median_value = np.median(values)
				closest_to_median_idx = np.argmin(np.abs(np.array(values) - median_value))
				peplist.drop(tmp.index.difference([tmp.index[closest_to_median_idx]]), inplace=True)

	# Save filtered IEDB data for postprocessing later
	columns_tosave = [col for col in peplist.columns if col != "Flag"]
	save_dir=os.getcwd()
	save_filename="IEDB_data.csv"

	print(f'\n{start_len-len(peplist)} records dropped')

	flagged_records=pd.DataFrame(columns=columns_tosave)
	if peplist["Flag"].any():
		flagged_records=peplist.loc[(peplist['Flag']==True)].sort_values(by='Epitope_ID')
		print('{} flagged records'.format(len(flagged_records)))
		peplist=peplist.drop(flagged_records.index.tolist())
		flagged_records.drop("Flag",axis=1,inplace=True)
		flagged_fn=os.path.join(save_dir,prefix+"flagged_"+save_filename)
		flagged_records.to_csv(flagged_fn, index=False)
		print(f'Flagged epitope data located in {flagged_fn}')

	# Final output for cleaned data
	print('{} records remaining'.format(len(peplist)))
	IEDB_fn=os.path.join(save_dir,prefix+"cleaned_"+save_filename)
	print(f"Filtered IEDB data written to {IEDB_fn}")
	peplist[columns_tosave].to_csv(IEDB_fn,index=False)

	# =======Build fasta
	fasta = peplist[['Epitope_ID','Description']]
	fasta_names = '>' + fasta['Epitope_ID'].astype(str)
	#fasta_names = fasta_names.tolist()
	fasta_sequences = fasta['Description'].tolist()

	fasta_fn = os.path.join(save_dir, prefix + 'IEDB_data.fasta')

	with open(fasta_fn, 'w') as fasta_fh:
		for name, sequence in zip(fasta_names, fasta_sequences):
			if '+' not in sequence:  # Final filter: remove sequences with non-canonical amino acids
				fasta_fh.write(name + '\n')
				fasta_fh.write(sequence + '\n')
		#else:
			#print(f"Omitting epitope {n}, sequence {s}")
			#commented out for simplicity

	print(f'Epitope sequences written to {fasta_fn}')
	return fasta_fn,peplist,flagged_records

def get_peplist(allele,assay_values):
	if isinstance(allele, str):
		allele = [allele]  # Fix for single allele case
	# First we need to get the list of HLA alleles we will be retrieving data for
	print("Retrieving data from IEDB for ",end="")
	notfound=[]

	if "all" in allele:
		print("all available alleles and ",end="")
		allele=["all"]

	else:
		# If allele is not set to all, retrieve the list of alleles
		allele_list=[]
		for a in allele:
			# Check if user passes a filename
			if "@" in a:
				fname=a[1:]
				if Path(os.path.abspath(fname)).is_file():
					with open(fname,"r") as f:
						allele_list.extend(f.read().splitlines())
				else:
					notfound.append(fname)
			else:
				allele_list.append(a)
		# Error-check the allele list to ensure it is properly formatted (remove new line characters and HLA- prefixes, etc.)
		allele = [a if a.startswith("HLA-") else "HLA-" + a for a in allele]
		print(f"{len(allele)} alleles and ",end="")

	assay_values=[ele.replace("_"," ") for ele in assay_values]
	print(f"the following assay values:\n{', '.join(assay_values)}")
	if len(notfound)>0:
		notify().warn("The following allele list files were passed by the user but not located:\n{}".format(', '.join(notfound)))

	# Make sure the local copy of the IEDB is present in <MHC database location>/build. If not, download it.
	dbloc=MHCdatabase().locate
	iedb_data_fn=os.path.abspath(os.path.join(dbloc,"build","mhc_ligand_full.csv"))
	IEDB_DATA_LOC="https://www.iedb.org/downloader.php?file_name=doc/mhc_ligand_full_single_file.zip"

	if not Path(iedb_data_fn).is_file():
		notify().warn(f"Local copy of IEDB not found. Attempting download...")
		try:
			success=True
			test_download=requests.get(IEDB_DATA_LOC)
			if test_download.status_code != 200:
				success=False
		except requests.exceptions.RequestException:
			success=False
		if not success:
			notify().error("Unable to obtain local copy of IEDB. Terminating execution.")
			return False
		else:
			iedb_data_zip_fn=os.path.join(os.path.dirname(iedb_data_fn),"IEDB_data.zip")
			iedb_data_zip=requests.get(IEDB_DATA_LOC, stream=True)
			with open(iedb_data_zip_fn, mode="wb") as f:
				for chunk in iedb_data_zip.iter_content(chunk_size=1024):
					if chunk:
						f.write(chunk)
			with ZipFile(iedb_data_zip_fn,"r") as zfile:
				zfile.extractall(path=os.path.dirname(iedb_data_zip_fn))
			os.remove(iedb_data_zip_fn)
			print(f"Local copy of IEDB downloaded to {iedb_data_fn}")

	#original headers
	#cols=['Epitope IRI','PubMed ID', 'Description', 'Parent Protein', 'Parent Protein IRI', 'Method/Technique', 'Assay Group', 'Quantitative measurement', 'PDB ID', 'Allele Name', 'MHC allele class']
	#updated headers
	#cols = [('Assay ID', 'IEDB IRI'), ('Reference', 'PMID'), ('Epitope', 'Name'), ('Epitope', 'Source Molecule'), ('Epitope', 'Source Molecule IRI'), ('Epitope', 'Source Organism'), ('Assay', 'Method'), ('Assay', 'Response measured'), ('Assay', 'Units'), ('Assay', 'Quantitative measurement'), ('Assay', 'PDB ID'), ('MHC Restriction', 'Name'), ('MHC Restriction', 'Class')]

	iedb_data = pd.DataFrame()
	chunksread=0
	chunksz=500000

	with pd.read_csv(iedb_data_fn, header=[0, 1], chunksize=chunksz, low_memory=False) as reader:
		for chunk in reader:
			chunk = flatten_columns(chunk)
			if allele[0] != "all":
				chunkdata = chunk[chunk['MHC Restriction Name'].isin(allele)]
			else:
				chunkdata_A = chunk[chunk['MHC Restriction Name'].str.contains("HLA-A*", regex=False)]
				chunkdata_B = chunk[chunk['MHC Restriction Name'].str.contains("HLA-B*", regex=False)]
				chunkdata_C = chunk[chunk['MHC Restriction Name'].str.contains("HLA-C*", regex=False)]
				chunkdata = pd.concat([chunkdata_A, chunkdata_B, chunkdata_C], ignore_index=True)

			filtered = chunkdata[chunkdata["Assay Response measured"].isin(assay_values)]
			iedb_data = pd.concat([iedb_data, filtered], ignore_index=True)

			chunksread += 1
			print(f"Epitopes processed: {chunksread*chunksz:<10}Epitopes found: {len(iedb_data):<10}", end="\r")

	print()
	if len(iedb_data)==0:
		notify().error(f"No epitopes with values for {assay_values} found in the IEDB!")
		return None

	#print("=======Data before deriving new columns:")
	#print(iedb_data.columns.tolist())
	# Clean the data a little to make it compatible with clean_peplist()
	iedb_data = iedb_data.astype({'Assay ID IEDB IRI': str, 'Epitope Epitope IRI': str, 'Epitope Source Molecule IRI': str})
	iedb_data = iedb_data.copy()  # Defragment
	iedb_data = standardize_columns(iedb_data)
	iedb_data = rename_columns(iedb_data)

	#print("=======Data after standardizing and renaming columns:")
	#print(iedb_data.columns.tolist())

	iedb_data["Epitope_ID"] = iedb_data["epitope_epitope_iri"].fillna("").apply(lambda x: x.split("/")[-1] if "/" in x else np.nan)

	iedb_data["Protein_Accession"] = iedb_data["epitope_source_molecule_iri"].fillna("").apply(lambda x: x.split("/")[-1] if "/" in x else np.nan)
	iedb_data.drop(columns=['epitope_epitope_iri', 'epitope_source_molecule_iri'], inplace=True)
	#print("=======Data after new columns:")
	#print(iedb_data.columns.tolist())

	iedb_data.columns = [c.title().replace("Id", "ID").replace("Pubmed", "PubMed").replace("Mhc", "MHC").replace("Iedb", "IEDB").replace("Iri", "IRI").replace("Pdb", "PDB") for c in iedb_data.columns]
	# Drop entries with missing values
	iedb_data.dropna(subset=["Epitope_ID", "Protein_Accession"], inplace=True)
	iedb_data.reset_index(inplace=True, drop=True)

	#print("=======Cleaned IEDB data:")  # debug
	#print(iedb_data.head())
	#print("Columns in cleaned IEDB data:", iedb_data.columns.tolist())
	#print("Sample Epitope Descriptions:")
	#print(iedb_data["Description"].dropna().unique()[:5])

	# For this next part we will create a separate IEDB and fasta files for each allele/epitope combination
	# We will also combine the cleaned, flagged, and fasta data into single combined files to be stored in the working directory
	allele_list=iedb_data['MHC_Restriction_Name'].unique().tolist()
	cwd=os.getcwd()
	epitope_count=0
	fasta_filenames=[]
	all_cleaned_data=pd.DataFrame()
	all_flagged_data=pd.DataFrame()

	for a in allele_list:
		safe_allele_name = a.replace(":", "_").replace("*", "_")  # <== fix folder name
		print(f"Processing epitopes for allele {a}")

		newpath=os.path.abspath(os.path.join(cwd, safe_allele_name))
		Path(newpath).mkdir(parents=True,exist_ok=True)

		os.chdir(newpath)
		print(f"Saving files to: {newpath}")

		allele_data = iedb_data[iedb_data["MHC_Restriction_Name"] == a]

		if allele_data.empty:
			print(f"No data found for allele {a}. Skipping.")
			os.chdir(cwd)
			continue  # Skip to next allele

		tmp_data = clean_peplist(allele_data, prefix=safe_allele_name + "_")
		if tmp_data[1].empty and tmp_data[2].empty:
			print(f"No cleaned or flagged data for allele {a}. Skipping.")
			os.chdir(cwd)
			continue

		fasta_filenames.append(tmp_data[0])
		final_column_rename_map = {"Description": "Epitope_Sequence", "Epitope_Molecule_Parent": "Parent_Protein", "Epitope_Source_Organism": "Source_Organism", "MHC_Restriction_Name": "Allele", "Assay_Response_Standardized": "Assay_Response"}

		all_cleaned_data_out = tmp_data[1].rename(columns=final_column_rename_map)
		all_flagged_data_out = tmp_data[2].rename(columns=final_column_rename_map)

		final_columns = ["Epitope_Sequence", "Epitope_ID", "PubMed_ID", "Parent_Protein", "Protein_Accession", "Source_Organism", "Allele", "Assay_Method", "Assay_Response", "Quantitative_Measurement", "Assay_Units", "MHC_Restriction_Class", "Assay_PDB_ID"]

		all_cleaned_data_out = all_cleaned_data_out[final_columns]
		all_flagged_data_out = all_flagged_data_out[final_columns]

		cleaned_data_fn = os.path.join(newpath, f"{safe_allele_name}_cleaned_IEDB_data.csv")
		flagged_data_fn = os.path.join(newpath, f"{safe_allele_name}_flagged_IEDB_data.csv")

		all_cleaned_data_out.to_csv(cleaned_data_fn, index=False)
		print(f"All cleaned IEDB data written to {cleaned_data_fn}")
		all_flagged_data_out.to_csv(flagged_data_fn, index=False)
		print(f"All flagged IEDB data written to {flagged_data_fn}")

		os.chdir(cwd)
	print(f"{int(epitope_count/2)} total epitopes written to fasta files for downstream processing")

	return fasta_filenames

def fasta_rebuild(fasta_fn, seq_toAdd):

	try:
		test=int(seq_toAdd)
	except:
		test=str(seq_toAdd).lower()
		if test=='false':
			notify().notice('Running pipeline with provided fasta file {}'.format(fasta_fn))
			return fasta_fn
	else:
		if int(seq_toAdd)==0:
			notify().notice('Running pipeline with provided fasta file {}'.format(fasta_fn))
			return fasta_fn

	if not os.path.isfile(os.path.abspath(fasta_fn)):
		sys.exit(notify().error('.fasta file {} does not exist!'.format(fasta_fn)))
	elif not os.path.isfile(seq_toAdd):
		sys.exit(notify().error('Curated sequences file {} does not exist!'.format(seq_toAdd)))

	seq_fh=open(seq_toAdd,'r')
	seq_data=seq_fh.readlines()[1::]
	seq_fh.close()

	fasta_fh=open(fasta_fn,'a')
	for i,l in enumerate(seq_data):
		tmp_data = l.split(',')
		if i==len(seq_data)-1:
			fasta_fh.write('>{}\n{}'.format(tmp_data[0],tmp_data[2]))
		else:
			fasta_fh.write('>{}\n{}\n'.format(tmp_data[0],tmp_data[2]))
	fasta_fh.close()

	print('Curated sequences added to {}'.format(fasta_fn))

	return fasta_filenames, all_cleaned_data, all_flagged_data

def add_NCAA(fasta_fn,params,position=False):

	fasta_fh = open(fasta_fn,"r")
	fasta_data = fasta_fh.readlines()
	fasta_fh.close()

	if not os.path.isfile(params):
		sys.exit(notify().error("Params file {} does not exist!".format(params)))
	else:
		params_fh=open(params,"r")
		ncaa_code=params_fh.readline().strip()
		ncaa_code=ncaa_code[-3::]
		print("NCAA 3-letter code: {}".format(ncaa_code))

	set_pos=False
	if position:
		try:
			int(position)
		except:
			notify().warn("{} is not a valid integer position. Ignoring in favor of default NCAA placeholder X".format(position))
		else:
			position=int(position)
			set_pos=True

	fasta_fh=open(fasta_fn,"w")
	numlines=len(fasta_data)
	seqcount=0
	for i,l in enumerate(fasta_data):

		tmpl=list(l.strip())

		if ">" not in tmpl and set_pos: #Make sure we have a sequence
			if position<=len(tmpl):
				tmpl[position-1]="X[{}]".format(ncaa_code)
				tmpl="".join(tmpl)
				fasta_fh.write(tmpl)
				seqcount+=1
				if i+1!=numlines:
					fasta_fh.write("\n")
			else:
				notify().warn("Position {} is out of range for sequence {} of length {}".format(position, "".join(tmpl), len(tmpl)))
				fasta_fh.write("".join(tmpl))
				if i+1!=numlines:
					fasta_fh.write("\n")
		elif ">" not in tmpl and not set_pos and "X" in tmpl: #If no position to replace is set, replace default placeholder value ("X")
			tmpl="".join(tmpl)
			tmpl=tmpl.replace("X","X[{}]".format(ncaa_code))
			fasta_fh.write(tmpl)
			seqcount+=1
			if i+1!=numlines:
					fasta_fh.write("\n")
		else:
			fasta_fh.write("".join(tmpl))
			if i+1!=numlines:
					fasta_fh.write("\n")

	fasta_fh.close()
	notify().notice("NCAA '{}' added to {} sequences".format(ncaa_code,seqcount))

	return

def create_batch_list(base_dir):
	# Open a file to store the batch list
	with open("batch_list.txt", "w") as f:
		# List all allele folders (subdirectories in the base directory)
		allele_folders = [f for f in os.listdir(base_dir) if os.path.isdir(os.path.join(base_dir, f))]
		# For each allele folder, get the FASTA file and create batches
		for allele in allele_folders:
			fasta_fn = os.path.join(base_dir, allele, 'sequence.fasta')  # Assuming FASTA file is named 'sequence.fasta'
			if os.path.isfile(fasta_fn):
				print(f"Processing FASTA file: {fasta_fn}")
				# Generate the batches using your existing make_batch function
				batchlist = make_batch(fasta_fn, size=25)  # Adjust the batch size if needed
				# Write each batch file path to the batch list
				for batch in batchlist:
					f.write(f"{batch}\n")
		print(f"Batch list saved to batch_list.txt")

def make_batch(fasta_fn, size=None):
	size = size or 25 # if size is None or 0, default to 25
	# Open file, read in sequence data and names as a dict, then define batch size
	with open(fasta_fn) as fh:
		lines = fh.readlines()
	fnames = lines[0::2]
	seqs = lines[1::2]

	# Initialize counters for batch and directory
	b_count = size  # Batch count iterator - keeps track of whether we need to make a new batch directory
	b_dir_count = 1  # Batch directory count - starts with 1 and adds 1
	base_dir = os.path.dirname(fasta_fn)  # Get the base directory where the FASTA file is located

	# Extract base name of the input FASTA file (without the '.fasta' extension)
	fasta_base_name = os.path.splitext(os.path.basename(fasta_fn))[0]

	# Construct the output directory structure
	output_dir = os.path.join(base_dir, 'output')  # Base output directory (e.g., 'output')
	os.makedirs(output_dir, exist_ok=True)  # Make the output directory if it doesn't exist

	# Causing problems with nested folders and batch1 overwriting
	# Folder for allele (e.g., HLA-A_01_01)
	#allele_folder = os.path.basename(base_dir)
	# Path for batch directories
	#batch_dir = os.path.join(output_dir, allele_folder, f'batch{b_dir_count}')

	# Use the base name of the input FASTA file as part of the batch directory name
	batch_dir = os.path.join(output_dir, f'{fasta_base_name}_batch{b_dir_count}')
	os.makedirs(batch_dir, exist_ok=True)  # Create the first batch directory

	tmp_fn = os.path.abspath(os.path.join(batch_dir, f'batch{b_dir_count}.fasta'))
	tmp_fh = open(tmp_fn, "w")

	seqdata = zip(fnames, seqs)
	blist = [tmp_fn]  # Keep track of our FASTA files

	for ind, (name, seq) in enumerate(seqdata):
		if ind > 0 and ind % size == 0:
			tmp_fh.close()
			b_dir_count += 1
			batch_dir = os.path.join(output_dir, f'{fasta_base_name}_batch{b_dir_count}')
			os.makedirs(batch_dir, exist_ok=True)

			tmp_fn = os.path.abspath(os.path.join(batch_dir, f'batch{b_dir_count}.fasta'))
			tmp_fh = open(tmp_fn, "w")
			blist.append(tmp_fn)
		tmp_fh.write(name)
		tmp_fh.write(seq)
	tmp_fh.close()
	return blist

##==postprocessing_affinity==##
def postprocessing_affinity(filtered_IEDB, scorefile, flagged_IEDB=[], topn=5, sortby="reweighted_sc"):

	if not os.path.isfile(filtered_IEDB):
		notify().error(f"{filtered_IEDB} is not a valid filename!")
		return
	elif not os.path.isfile(scorefile):
		notify().error(f"{scorefile} is not a valid filename!")
		return

	prog_bar=progressBar(blen=40,bcolor1='red',bcolor2='black')
	prog_bar.update(0.1,pmsg=f"Imported data from {os.path.basename(filtered_IEDB)} and {os.path.basename(scorefile)}")
	filtered_IEDB_data = pd.read_csv(filtered_IEDB)
	score_data = pd.read_csv(scorefile)

	if len(flagged_IEDB)>0:
		if not os.path.isfile(flagged_IEDB):
			warnmsg=notify().warn(f"{flagged_IEDB} is not a valid file! Proceeding with postprocessing but omitting flagged epitopes...",toprint=False)
			prog_bar.update(0,pmsg=warnmsg)
			sleep(1)
		else:
			flagged_IEDB_data = pd.read_csv(flagged_IEDB)
			filtered_IEDB_data=pd.concat([filtered_IEDB_data, flagged_IEDB_data], ignore_index=True)

	# Set epitope names for input scorefile data (format for description column should be <epitopeName>_<input>_<decoynum> for input files named by thread_all() )
	dnames = score_data["description"].tolist()
	epitope_names = []
	for n in dnames:
		epitope_names.append(n.split("_")[0])

	# Drop values in scoredata that do no not match filtered IEDB data

	score_data["Epitope_ID"]=epitope_names # Add a column to store our Epitope_IDs
	score_data["Quantitative_Measurement"]=''
	enames=score_data["Epitope_ID"].unique().tolist()

	todrop=[]
	for name in enames:
		try:
			BA_tmp=filtered_IEDB_data["Quantitative_Measurement"].loc[filtered_IEDB_data["Epitope_ID"]==int(name)].tolist()[0]
		except:
			todrop.append(name)

	if len(todrop)>0:
		for d in todrop:
			score_data.drop(score_data.index[score_data["Epitope_ID"]==d], inplace=True)
		score_data.to_csv(f"dropped_{os.path.basename(scorefile)}")
		prog_bar.update(0,pmsg=f"{len(todrop)} records dropped from {scorefile}. Updated scorefile written to dropped_{os.path.basename(scorefile)}")

	inc=(1/len(enames))*0.9
	for name in enames:
		prog_bar.update(inc,msg=f"Processing epitope {name}")
		# Retrieve the binding affinity value
		try:
			BA_tmp=filtered_IEDB_data["Quantitative_Measurement"].loc[filtered_IEDB_data["Epitope_ID"]==int(name)].tolist()[0]
		except:
			prog_bar.update(0,msg=f"Epitope {name} not found")
			continue
		score_data.loc[score_data["Epitope_ID"]==name,"Quantitative_Measurement"]=BA_tmp

	score_data.to_csv(f"affinity_{os.path.basename(scorefile)}", index=False)
	prog_bar.update(0.05,msg=f"Appended score data written to affinity_{os.path.basename(scorefile)}")

	prog_bar.update(0.05,msg="Processing epitopes complete")


	print("\nGenerating Statistics...")
	stats_from_scorefile(f"affinity_{os.path.basename(scorefile)}", topn=topn, sortby=sortby)
	return

##==build_scorefile==##
def build_scorefile(sdir, sortby=["reweighted_sc"], get_top_mod=0, params=None):
	# Utility for creating a summary .csv file from a folder full of .silent files containing scoredata from the production run
	# Inputs:
	#  sdir 	Directory with silent files (mandatory)
	#  sortby	Sort resultant scores by this category. If multiple values passed, sorts in priority order
	#  get_top_mod	gets N top models in order specified by sortby
	#  params 	Path to Rosetta params file if .silent file structures contain NCAA (only needed if get_top_mod passed)
	pd.options.display.max_columns = 999
	sdir = os.path.abspath(sdir)

	bar=progressBar(blen=30,bcolor1='red')

	# Build a scorefile from a directory of silent files. General strategy:
	# 1. Iterate through the directory and identify a silent file as a file with the extension ".silent"
	# 2. Open the file and read the lines. Retrieve the header categories if not already retrieved (a header line will have the string "description". Otherwise, identify the score data with the string "SCORE:", and append that data to a growing list
    # 3. Keep track of which silent file contains which score data so we can backtrace good models for figures/further analysis. Save these in the list "flist" and append to the dataframe with the column titled "file_name"
	out_lines=[]
	dir_contents="{} contents:".format(sdir)
	inc=1/len(os.listdir(sdir))
	scorelist = []
	flist=[]
	foundheaders = False
	for f in os.listdir(sdir):
		if ".silent" in f:
			bar.update(inc,msg=f"Now reading scoredata from {f[0:-8]:>10}")
			tmp_fh=open(os.path.join(sdir,f))
			out_lines=tmp_fh.readlines()
			tmp_fh.close()
			for l in out_lines:
				if not foundheaders:
					if 'description' in l:
						headers = l.split()
						foundheaders = True
					elif "SCORE:" in l:
						scorelist.append(l.split())
						flist.append(f)
				elif "SCORE:" in l and "description" not in l:
					scorelist.append(l.split())
					flist.append(f)
		else:
			bar.update(inc)
		dir_contents=dir_contents+"{}\n".format(f)

	if len(out_lines)==0:
		warnmsg=notify().warn(f"No .silent files located in {sdir}!",toprint=False)
		bar.update(0,pmsg=warnmsg)
		bar.update(0,pmsg=f"{dir_contents}")
		return False

	# Include silent file names for each entry so we don't lose track when we go to extract models
	scoredata = pd.DataFrame(data=scorelist,columns=headers)
	scoredata["file_name"]=flist
	sort_key=["description"]
	not_found=[]
	for s in sortby:
		if s in headers:
			sort_key.append(s)
		else:
			not_found.append(s)

	# A little check to see if the user passed invalid inputs
	if len(not_found)>0:
		notify().warn("{} not located!\n\nSorting on: {}\n\nAvailable headers include:\n{}\n\n".format(", ".join(not_found), ", ".join(sort_key), "\n".join(headers)))

	# # Right now just sorts by "reweighted_sc"
	# print("\nNow sorting by: {}".format(", ".join(sort_key)))
	# scoredata.apply
	# scoredata[sort_key[0]]=scoredata[sort_key[0]].apply(pd.to_numeric)
	# scoredata.sort_values(sort_key,ignore_index=True, inplace=True, ascending=True)
	
	scoredata.to_csv(os.path.join(sdir,"sorted_scores.sc"),index=False)
	scname=os.path.join(sdir,"sorted_scores.sc")

	print("sorted_scores.sc created")
	if get_top_mod>0:
		print("Top scoring models:")
		print(scoredata[["description","file_name",sortby[-1],"rmsBB"]].iloc[0:get_top_mod])
		args=[os.environ.get("PEPBIND3D_ROSETTA", "/dors/meilerlab/apps/rosetta/rosetta-3.14/main") + "/source/bin/extract_pdbs.linuxgccrelease","-in:file:silent"]

		struct_names=scoredata["description"].iloc[0:get_top_mod].tolist()
		silent_names=scoredata["file_name"].iloc[0:get_top_mod].tolist()

		for i,struct in enumerate(struct_names):
			tmp_args=args+[os.path.join(os.path.abspath(sdir),silent_names[i]),"-in:file:tags",struct, "-out:prefix", silent_names[i]+"_"]
			if params != None:
				if Path(params).is_file():
					tmp_args.extend(["-extra_res_fa",params])
			subprocess.run(tmp_args)

	return scname

##==stats_from_scorefile==##
def stats_from_scorefile(scorefile, sortby="I_sc", topn=5):

	import pandas as pd
	import math
	import numpy as np
	from formats import progressBar
	# Assumes scorefile with "Epitope_ID" and "Quantitative_measurement" columns as generated by postprocessing_affinity

	prog_bar=progressBar(blen=30,bcolor1="red")

	score_data=pd.read_csv(scorefile)
	new_data=pd.DataFrame(columns=score_data.columns.tolist())
	score_data.sort_values(["Epitope_ID", sortby], inplace=True)

	enames=score_data["Epitope_ID"].unique().tolist()
	enames=list(set(score_data["Epitope_ID"].tolist()))
	
	average_reu=[]
	std_reu=[]
	BA_logIC50=[]

	resolution_reu=100 # Data to determine how many REU thresholds we will calculate statistics for

	# Most relevant thresholds for statistics calculations. <50nm is a strong binder, >50<500 is a weak binder, and >500 is a nonbinder.
	thresholds_logIC50=[math.log10(50), math.log10(500)]

	prog_bar.update(0.1, msg=f"Computing average binding affinities for top {topn} models")
	for e in enames:
		tmp_data=score_data.loc[(score_data["Epitope_ID"]==e)]
		new_data=pd.concat([new_data,tmp_data.iloc[:(topn+1)]],ignore_index=True) #for output file
		average_reu.append(tmp_data[sortby].iloc[:(topn+1)].mean()) #averages
		std_reu.append(tmp_data[sortby].iloc[:(topn+1)].std()) #stdevs
		BA_logIC50.append(math.log10(tmp_data["Quantitative_Measurement"].iloc[0])) #all values for a given epitope should be identical
	prog_bar.update(0,pmsg=f"Computed average binding affinities for top {topn} models")

	thresholds_reu=np.linspace(min(average_reu)+1,max(average_reu)-1,num=resolution_reu)

	fn_suffix="sortby-{}_topn-{}".format(sortby,topn)
	graph_fn="graphData_{}.csv".format(fn_suffix)
	prog_bar.update(0.1,msg="Writing average REU values for top {} models and corresponding binding affinity to {}".format(topn,graph_fn))

	pd.DataFrame({"Binding Affinity (log10(IC50))": BA_logIC50, "Average REU": average_reu, "STDEV": std_reu}).to_csv(graph_fn, index=False)

	prog_bar.update(0,pmsg=f"ROC statistics written to {graph_fn}")

	# What we need: average value for each epitope, along with +/-SD
	# Threshold value for "strong" vs "weak" binder
	# For each threshold, build an ROC and output to a file named threshold_ROC.csv
	# Also output a file that has test statistics for each threshold:
	# 	TP, FP, TN, FN, PPV, NPV, FDR, +LR, -LR, prevalence, accuracy
	#   ROC x axis (1-specificity, or FP/FP+TN)
	# 	ROC y axis (sensitivity, or TP/TP+FN)

	# Now for each threshold calculate the statistics above. First classify all
	# of our values as "BINDER" or "NONBINDER" based on predefined log10(IC50) cutoffs (this is the true value). Then, iterate through the rosetta REU thresholds and calc the table of stats above. For each threshold classifier, find the optimal AUC value (i.e. the highest) and report the statistics for the test as shown.

	AUC=[]
	prevalence=[]
	optimal_REU_thresh_energy=[]
	optimal_REU_thresh_accuracy=[]
	for ind,thresh in enumerate(thresholds_logIC50):
		TP_rate=[]
		TN_rate=[]
		FP_rate=[]
		FN_rate=[]
		PPV=[]
		NPV=[]
		FDR=[]
		LR_pos=[]
		LR_neg=[]
		accuracy=[]
		jstat=[]
		prog_bar.update(0.2,msg="Computing statistics for log10(IC50) threshold {}".format(thresh))
		thresh_true = []
		for i in range(0,len(enames)): # Determine binder classification (true positives)
			if BA_logIC50[i]<=thresh:
				thresh_true.append(True)
			else:
				thresh_true.append(False)
		
		prevalence.append(sum(thresh_true)/len(thresh_true))
		
		# Define x,y pairs for ROC:
		one_minus_spec=[]
		sens=[]
		for reu_cutoff in thresholds_reu: # Now determine ROC and AUC
			# For each cutoff tested we need an (x,y) pair for the ROC
			TP = []
			TN = []
			FP = []
			FN = []
			for i in range(0,len(enames)):
				TP.append(thresh_true[i] and (average_reu[i]<=reu_cutoff)) 
				TN.append(thresh_true[i]==False and (average_reu[i]>reu_cutoff))
				FP.append(thresh_true[i]==False and (average_reu[i]<=reu_cutoff))
				FN.append(thresh_true[i] and (average_reu[i]>reu_cutoff))
			
			FP_sum=sum(FP)
			TN_sum=sum(TN)
			TP_sum=sum(TP)
			FN_sum=sum(FN)
			# print(reu_cutoff)
			# print("FP: {}".format(FP_sum))
			# print("TN: {}".format(TN_sum))
			# print("TP: {}".format(TP_sum))
			# print("FN: {}".format(FN_sum))
			one_minus_spec.append(FP_sum/(FP_sum+TN_sum))

			calc=True
			try:
				TP_sum/(TP_sum+FN_sum)
			except ZeroDivisionError:
				TP_rate.append(np.inf)
				sens.append(np.inf)
				FN_rate.append(np.inf)
				calc=False
			if calc:
				sens.append(TP_sum/(TP_sum+FN_sum))
				TP_rate.append(TP_sum/(TP_sum+FN_sum)) # Recall, same as sensitivity
				FN_rate.append(FN_sum/(FN_sum+TP_sum))
			
			FP_rate.append(FP_sum/(FP_sum+TN_sum))
			TN_rate.append(TN_sum/(TN_sum+FP_sum)) # Specificity
			

			PPV.append(TP_sum/(TP_sum+FP_sum)) # Precision
			NPV.append(TN_sum/(TN_sum+FN_sum))
			FDR.append(FP_sum/(FP_sum+TP_sum))
			LR_pos.append(TP_rate[-1]/FP_rate[-1])
			LR_neg.append(FN_rate[-1]/TN_rate[-1])
			accuracy.append((TP_sum+TN_sum)/(len(thresh_true)))
			jstat.append(TP_rate[-1]+TN_rate[-1]-1)

		ROC_xy=sorted(zip(one_minus_spec,sens), key=lambda k: k[0])
		tmp=0
		for i in range(0,len(sens)-1):
			x1=ROC_xy[i][0]
			x2=ROC_xy[i+1][0]
			y1=ROC_xy[i][1]
			y2=ROC_xy[i+1][1]
			tmp=tmp+(x2-x1)*(y1+0.5*(y2-y1))
		
		AUC.append(tmp)
		tmp_stats={"REU Threshold": thresholds_reu, "TP (Recall)": TP_rate, "FP": FP_rate, "TN (Specificity)": TN_rate, "FN": FN_rate, "PPV (Precision)": PPV, "NPV": NPV, "FDR": FDR, "Positive Likelihood Ratio": LR_pos, "Negative Likelihood Ratio": LR_neg, "Accuracy": accuracy, "J-statistic": jstat}
		tmp_stats_df=pd.DataFrame(tmp_stats)
		tmp_fn="IC50-{}_statistics_{}.csv".format(round(10**thresh), fn_suffix)
		prog_bar.update(0.2,pmsg="Writing statisitcs for IC50 {}nm to {}".format(round(10**thresh), tmp_fn))
		tmp_stats_df.to_csv(tmp_fn, index=False)

		# Find the optimal REU threshold based on accuracy:
		optimal_REU_thresh_tmp=max(zip(thresholds_reu, accuracy), key=lambda x: x[1])
		optimal_REU_thresh_energy.append(optimal_REU_thresh_tmp[0])
		optimal_REU_thresh_accuracy.append(optimal_REU_thresh_tmp[1])

	thresholds_fn="summaryStatistics_{}.csv".format(fn_suffix)
	prog_bar.update(0.2,msg="Writing summary statistics for all thresholds to {}".format(thresholds_fn))

	pd.DataFrame({"Thresholds (log10(IC50)": [round(10**x) for x in thresholds_logIC50], "ROC CDF (AUC)": AUC, "Optimal {} Threshold".format(sortby): optimal_REU_thresh_energy, "Accuracy": optimal_REU_thresh_accuracy}).to_csv(thresholds_fn, index=False)

	return

##========================== thread_template ==========================##
def thread_template(input_fasta, db, ROSETTA_PATH, params=False, user_defined_receptor=None, ignore_perfect_match=False, find_worst_template=False):
	# Subroutine that takes in an input peptide, path to database with aligned peptide/MHC complexes, and desired allele
	# Finds a matching peptide with the best sequence identity then threads the input peptide onto the corresponding model
 	# Takes the threaded model and writes a rosetta_scripts.xml file to generate an input structure for flexpepdock refinement
 	# Optionally takes in a params file (with the position denoted by "X[NCAA]" in the input_fasta file), and incorporates the NCAA into the final starting model by mutating the amino acid at the appropriate position.
 	# Fasta files with NCAA should be formatted per Rosetta guidelines (i.e., NCAA should be designated "X[NCAA_name]")

 	# Create the allele - we will need to make sure it has a receptor present in the database as well
 	allele=db.allele
 	if user_defined_receptor!=None and Path(user_defined_receptor).is_file():
 		chk_success=db.set_allele(allele, build_receptor=False)
 	else:
 		chk_success=db.set_allele(allele)# This will automatically build the receptor if it is not present and create a list of alleles in the structure database to use as peptide backbone templates. Building a receptor with AlphaFold2 could take upwards of ~1h
 	if not chk_success:
 		notify().error(f"Failed to set allele to {allele}")
 		#print(f"DEBUG: db.set_allele returned {chk_success}")
 		return False

	# Retrieve the peptide sequences in the structural database for either the allele or (if unavailable) its next nearest sequence neighbor
 	struct_data_fn=os.path.join(db.locate,"database.info")
 	if Path(struct_data_fn).is_file():
 		struct_data=pd.read_csv(struct_data_fn)
 	else:
 		notify().error(f"Unable to locate {struct_data_fn}! Does it exist?")
 		#print(f"DEBUG: Checking for {struct_data_fn} -> Exists? {Path(struct_data_fn).is_file()}")
 		return False

 	# Retrieve the default receptor location
 	receptor_default=db.receptor

 	# Import the fasta file for the sequence to thread
 	input_record = SeqIO.read(input_fasta, "fasta")
 	input_record_originalSeq = input_record.seq

 	# Handle NCAA sequences if present
 	if "X" in input_record.seq:
 		if not params:
 			notify().error(f"NCAA placeholder 'X' found in {input_fasta}, but no params file provided.")
 			#print(f"DEBUG: NCAA handling - params provided? {params}")
 			return False
 		else:
 			with open(os.path.abspath(params), "r") as pfile:
 				NCAA_name = pfile.readline().strip()[-3:]
 			input_record.seq = Seq(str(input_record.seq).replace(f"[{NCAA_name}]", ""))

 	# Template selection logic
 	to_omit = ["self"] if ignore_perfect_match else []
 	template_id_method = "worst" if find_worst_template else "best"

 	queryseq = str(input_record.seq) if "X" in input_record.seq else str(input_record_originalSeq)

 	# Retrieve multiple ranked templates
 	template_candidates = db.get_peptide_template(queryseq, method=template_id_method, omit=to_omit)
 	if not template_candidates:
 		notify().error(f"DEBUG: No valid templates found for sequence: {queryseq}")
 		print(f"DEBUG: Found {len(template_candidates)} templates for {queryseq}")
 		return False

 	# Define parent directory and log file
 	parent_dir = os.path.abspath(os.path.dirname(input_fasta))
 	log_file = os.path.join(parent_dir, f"{os.path.basename(input_fasta)[:-6]}_ROSETTA.log")
 	print(f"DEBUG: Log file will be saved to {log_file}")

 	print(f"DEBUG: Found {len(template_candidates)} template(s) for sequence {queryseq}")
 	if len(template_candidates) == 0:
 		notify().error(f"No templates found for {queryseq}")
 		return False

 	# Try each template until one succeeds
 	for best_pdb in template_candidates:
 		best_pdb_fn = os.path.abspath(os.path.join(db.locate, "templates", best_pdb + ".pdb"))
 		XML_filename = os.path.join(parent_dir, f"flexpepdock_input_{os.path.basename(input_fasta)[:-6]}.xml")

 		# Retrieve template sequence
 		best_sequence_data = db.query_mhc_database(gettemplate=best_pdb, quiet=True)[0]
 		best_sequence = best_sequence_data["Epitope_Description"]

 		# Get chain information
 		db_records = pd.read_csv(os.path.join(db.locate, "database.info"))
 		pChain = db_records["Antigen_PDB_Chain(s)"].loc[db_records["PDB_ID"] == best_pdb].values[0]
 		mhcChain = db_records["MHC_PDB_Chain1"].loc[db_records["PDB_ID"] == best_pdb].values[0]

 		# STEP 1: Generate XML for SimpleThreadingMover
 		root = ET.Element("ROSETTASCRIPTS")

 		scorefxns = ET.SubElement(root, "SCOREFXNS")
 		ET.SubElement(scorefxns, "ScoreFunction", name="score", weights="ref2015")

 		movers = ET.SubElement(root, "MOVERS")
 		protocols = ET.SubElement(root, "PROTOCOLS")

 		if "X" in input_record.seq:
 			modified_seq = input_record.seq.replace("X", "X[KIS]")
 		else:
 			modified_seq = input_record.seq
 		if "X" in input_record.seq and not params:
 			print(f"DEBUG: Params file missing for NCAA sequence {input_fasta}")
 			notify().error(f"NCAA placeholder 'X' found in {input_fasta}, but no params file provided.")
 			return False


 		start_pos = "1" if not pChain or pChain == "0" else f"1{pChain}"  # Default to "1" if pChain is empty or invalid
 		ET.SubElement(movers, "SimpleThreadingMover", name="threadModel", pack_neighbors="1", 		start_position=start_pos, thread_sequence=modified_seq, skip_unknown_mutant="1", pack_rounds="1")
 		ET.SubElement(protocols, "Add", mover="threadModel")
 		#print(f"DEBUG: Assigned start_position='{start_pos}' in XML")  # Debugging

 		# STEP 1b: Mutate NCAA if present
 		if params:
 			params_path = os.path.abspath(params)  # Ensure absolute path
 			params_dest = os.path.join(parent_dir, os.path.basename(params))  # Destination in working dir

 			# Copy NCAA params file to working directory
 			shutil.copyfile(params_path, params_dest)

 			# Copy associated rotamer file if it exists
 			rotamers_fn = None
 			with open(params_path, "r") as pfile:
 				last_line = pfile.readlines()[-1].strip()  # Read last line
 				#print(f"DEBUG: Last line of params file -> {last_line}")
 				if last_line.startswith("PDB_ROTAMERS"):  # Ensure correct line
 					rotamers_fn = os.path.join(os.path.dirname(params_path), last_line.split(" ")[1])

 			if rotamers_fn:
 				print(f"DEBUG: Searching for rotamer file at {rotamers_fn}")
 			# If the rotamer file exists, copy it
 			if rotamers_fn and os.path.exists(rotamers_fn):
 				shutil.copyfile(rotamers_fn, os.path.join(parent_dir, os.path.basename(rotamers_fn)))
 				#print(f"DEBUG: Copied NCAA rotamer file {rotamers_fn} to {parent_dir}")
 			else:
 				print("WARNING: No valid rotamer file found! NCAA mutation may fail. Expected at {rotamers_fn}")
 			if os.path.exists(rotamers_fn):
 				shutil.copyfile(rotamers_fn, os.path.join(parent_dir, os.path.basename(rotamers_fn)))
 				#print(f"DEBUG: Copied NCAA rotamer file to {parent_dir}")
 			for i, AA in enumerate(input_record.seq):
 				if AA == "X":
 					tmp_pos = i + 1
 					ET.SubElement(protocols, "Add", mover=f"mutateRes_{tmp_pos}")
 					ET.SubElement(movers, "MutateResidue", name=f"mutateRes_{tmp_pos}",
                                  target=f"{tmp_pos}{pChain}", new_res=NCAA_name)
 			if 'args' not in locals():
 				args = []
 			args.extend(["-extra_res_fa", os.path.abspath(params)])

 		# STEP 2: Delete overhanging residues
 		N = len(best_sequence) - len(input_record.seq)

 		# Ensure chain alignment
 		from Bio.PDB import PDBParser
 		pdb_parser = PDBParser(QUIET=True)
 		structure = pdb_parser.get_structure("template", best_pdb_fn)
 		model = structure[0]
 		chain = model[mhcChain]
 		template_rescount = sum(1 for _ in chain)
 		# Highest residue NUMBER in the MHC chain. This differs from the residue
 		# COUNT whenever the chain has numbering gaps (unresolved residues), and
 		# the receptor trim below needs the number, not the count: deleting
 		# 182..count leaves every residue numbered above the count behind as a
 		# spurious extra chain.
 		template_resmax = max((r.id[1] for r in chain if r.id[0] == " "), default=template_rescount)

 		receptor_default = db.receptor

 		replace_receptor_fn = os.path.abspath(user_defined_receptor) if user_defined_receptor and Path(user_defined_receptor).is_file() else receptor_default

 		#print(f"DEBUG: user_defined_receptor = {user_defined_receptor}")
 		#print(f"DEBUG: receptor_default = {receptor_default}")
 		#print(f"DEBUG: using receptor file -> {replace_receptor_fn}")

 		new_receptor_fn = os.path.join(parent_dir, "tmp_receptor.pdb")
 		#print(f"DEBUG: new_receptor_fn assigned -> {new_receptor_fn}")

 		if not Path(replace_receptor_fn).is_file():
 			print(f"ERROR: Expected receptor file {replace_receptor_fn} does not exist!")
 			return False  # Exit early if receptor file is missing

 		try:
 			new_receptor = pdb_parser.get_structure("defaultReceptor", replace_receptor_fn)
 		except Exception as e:
 			print(f"ERROR: pdb_parser.get_structure failed! Exception: {e}")
 			return False

 		io = PDBIO()
 		found_chain_A = False

 		for chain in new_receptor.get_chains():
 			print(f"DEBUG: Checking chain {chain.get_id()} in new_receptor")
 			if chain.get_id() == "A":
 				found_chain_A = True
 				io.set_structure(chain)
 				io.save(new_receptor_fn)
 				print(f"Successfully saved receptor to {new_receptor_fn}")

 		if not found_chain_A:
 			print(f"ERROR: Chain 'A' not found in receptor structure!")
 			return False

 		if not os.path.exists(new_receptor_fn):
 			print(f"ERROR: new_receptor_fn {new_receptor_fn} does not exist before using it.")
 			return False

 		structure = pdb_parser.get_structure("receptor", new_receptor_fn)
 		model = structure[0]
 		chain = model["A"]
 		receptor_rescount = sum(1 for _ in chain)

 		# Ensure deletion only delete residues within the valid range
 		if N > 0:
 			delete_start = len(input_record.seq) + 1
 			delete_end = min(len(best_sequence), template_rescount)

 			if delete_start <= template_rescount:
 				ET.SubElement(protocols, "Add", mover="deleteRes")
 				ET.SubElement(movers, "DeleteRegionMover", name="deleteRes", start=f"{delete_start}{pChain}", end=f"{delete_end}{pChain}")

 		# STEP 3: Add receptor
 		# If the template is longer, remove extra residues
 		resdiff = template_rescount - receptor_rescount
 		if resdiff > 0:
 			# Trim to the highest residue NUMBER, not the residue count. On a
 			# chain with numbering gaps count < max number, so trimming to the
 			# count leaves every residue numbered above it behind as a spurious
 			# chain of untrimmed receptor whose size equals the gap count.
 			trim_end = template_resmax
 			ET.SubElement(protocols, "Add", mover="deleteRes_receptor")
 			ET.SubElement(movers, "DeleteRegionMover", name="deleteRes_receptor",
                  start=f"{receptor_rescount + 1}{mhcChain}",
                  end=f"{trim_end}{mhcChain}", rechain="1")

 		chaindict = {chr(i): i - 64 for i in range(65, 91)}
 		mhcChain = db_records["MHC_PDB_Chain1"].loc[db_records["PDB_ID"] == best_pdb].values[0]
 		if mhcChain in chaindict:
 			chain_toSwap = chaindict.get(mhcChain, 1)
 		else:
 			notify().error(f"Unrecognized chain ID '{mhcChain} in {best_pdb}. Defaulting to 'A'.")
 			chain_toSwap = 1

 		ET.SubElement(protocols, "Add", mover="addReceptor")
 		ET.SubElement(movers, "AddChain", name="addReceptor", file_name=new_receptor_fn, swap_chain_number=str(chain_toSwap))

 		# STEP 4: FastRelax after prepack
 		ET.SubElement(protocols,"Add", mover="fastrelax")
 		ET.SubElement(movers, "FastRelax", name="fastrelax", repeats="5", scorefxn="score")

 		# STEP 5: Run FlexPepDock prepack
 		ET.SubElement(protocols, "Add", mover="prepack")
 		ET.SubElement(movers, "FlexPepDock", name="prepack", ppk_only="1")
    
 		# Write XML file
 		#print(f"DEBUG: Preparing to write XML file at {XML_filename}")
 		os.makedirs(os.path.dirname(XML_filename), exist_ok=True)
 		xmltree = ET.ElementTree(root)
 		ET.indent(xmltree, space='    ')
 		#print(f"DEBUG: Writing XML file now...")
 		xmltree.write(XML_filename)

 		# Ensure XML file was created
 		if os.path.exists(XML_filename):
 			print(f"DEBUG: XML file successfully written at {XML_filename}")
 		else:
 			print(f"DEBUG: XML failed to write at {XML_filename}")
 			return False

 		###### Debugging
 		required_files = {
 			"Template PDB": best_pdb_fn,
 			"XML Protocol": XML_filename,
 			"Receptor PDB": replace_receptor_fn if user_defined_receptor else "N/A",
 		}
 		if params:
 			required_files["Params File"] = params

 		for name, file in required_files.items():
 			if file != "N/A" and not os.path.exists(file):
 				print(f"ERROR: {name} not found -> {file}")
 				return False  # Stop execution if a required file is missing

 		print("All required files exist. Proceeding with Rosetta...", flush=True)

 		# Run Rosetta 
 		notify().notice(f"Running Rosetta with template {best_pdb}")
        
 		args = []
 		#log_file = os.path.join(parent_dir, f"{os.path.basename(input_fasta)[:-6]}_rosetta.log")
 		args = [f"{ROSETTA_PATH}/source/bin/rosetta_scripts.linuxgccrelease", "-s", best_pdb_fn, "-parser:protocol", XML_filename, "-database", f"{ROSETTA_PATH}/database", "-overwrite", "-out:level", "300"]
 		# "-mute", "all"
 		# Load depositor coordinates flagged occupancy=0. Rosetta drops
 		# zero-occupancy atoms by default, so a template whose peptide has an
 		# unresolved middle loads short and the threaded query is silently
 		# truncated (1QR1: 9 peptide CA but only 6 Rosetta-loadable, so a 9-mer
 		# threads as 6). The disordered coordinates are still a valid starting
 		# placement: the anchors are resolved and FastRelax + FlexPepDock
 		# -pep_refine resample the peptide anyway.
 		args.extend(["-ignore_zero_occupancy", "false"])
 		if params and os.path.exists(params):
 			args.extend(["-extra_res_fa", os.path.abspath(params)])

 		print(f"DEBUG: Running Rosetta with command:\n{' '.join(args)}", flush=True)

 		try:
 			with open(log_file, "w") as f:
 				print(f"DEBUG: Running Rosetta, logging to {log_file}", flush=True)
 				p = subprocess.run(args, stdout=f, stderr=f)

 			# Rename the output .pdb file
 			output_pdb_fn = os.path.join(parent_dir, "{}_0001.pdb".format(best_pdb))

 			# Check if Rosetta produced the expected PDB file
 			if os.path.exists(output_pdb_fn):
 				print(f"\n{output_pdb_fn} saved and ready for production.", flush=True)

 				# Rename the output .pdb file
 				output_fn_new = os.path.join(parent_dir, "{}_input.pdb".format(os.path.basename(input_fasta)[0:-6]))

 				# Ensure old file exists before renaming to avoid errors
 				if os.path.exists(output_pdb_fn):
 					shutil.move(output_pdb_fn, output_fn_new)
 					print(f"Renamed {output_pdb_fn} to {output_fn_new}")
 					return output_fn_new  # Return the renamed PDB file
 				else:
 					print(f"Warning: {output_pdb_fn} not found. Renaming skipped.")
 					return output_pdb_fn  # Return the original file if renaming failed
 			else:
 				notify().error(f"Expected output {output_pdb_fn} not found. Check Rosetta output.")

 		except subprocess.CalledProcessError:
 			print(f"Rosetta failed with template {best_pdb}. Trying next template...")
 	# If no templates worked
 	notify().error(f"All templates failed for {queryseq}. Skipping.")
 	return False

##========================== thread_all ==========================##

def thread_all(peptide_list, mhcdb, ROSETTA_PATH, user_defined_receptor=None, params=False, for_production=[True,True], ignore_perfect_match=False, find_worst_template=None):
	# Wrapper for thread_template. Will make a folder and produce a prepacked starting model for each sequence. Optionally 
	# writes a slurm file and flexpepdock options file from templates for each peptide so prepared.
	# Variables:
	# 	peptide_list: A fasta file or text file with a list of epitope sequence(s)
	#	allele: MHC allele to dock to
	#	ROSETTA_PATH: path to local installation of Rosetta
	#	user_defined_receptor: .pdb file to use as MHC receptor (optional)
	#	params: path to Rosetta .params file for any NCAA (optional)
	#	for_production: list with slurm and options variables and values to create .slurm and .options files for a flexpepdock refinement production run
	#	ignore_perfect_match: Optional variable to set in order to avoid using the input epitope as its own sequence, if it has a structure available in the template database

	parent_dir = os.path.dirname(peptide_list) # The directory where the fasta file is located
	allele=mhcdb.allele
	# Set default slurm options as a dict
	slurm_options= {"mail-user": os.environ.get("PEPBIND3D_SLURM_MAIL", ""), "mail-type": "FAIL", "ntasks": "1", "time": "45:00:00", "mem": "1G", "output": os.environ.get("PEPBIND3D_SLURM_LOGDIR", ".") + "/%A-%a.log"}

	if for_production[0]: # Update slurm_options with user values, if applicable
		update_slurm_options=[]
		update_slurm_values=[]
		for s in for_production[0]:
			if "=" in s:
				tmpvals = s.split("=")
				update_slurm_options.append(tmpvals[0])
				update_slurm_values.append(tmpvals[1])
				if len(tmpvals)>2:
					notify().warn("Provided slurm #SBATCH option '{}' has multiple values assigned. Only the first ({}) will be used\033[0m".format(tmpvals[0], tmpvals[1]))
			else:
				notify().warn("Provided slurm #SBATCH option '{}' has no assigned value and will be ignored\033[0m".format(s))
		
		sbatch_toupdate = dict(zip(update_slurm_options, update_slurm_values))
		slurm_options.update(sbatch_toupdate)
		print("New #SBATCH variable/option pairs to be written to file:")
		for key, value in slurm_options.items():
			print("{} = {}".format(key, value))

	options_list=[]
	if for_production[1]: # Parse updated command line arguments, if applicable
		print("\nSetting command line options:")
		options = for_production[1]
		for option in options:
			if "=" in option:
				tmpvals=option.split("=")
				tmpvals[0]="-{}".format(tmpvals[0])
				options_list.append(tmpvals[0])
				options_list.append(tmpvals[1::])
				print(" ".join(tmpvals))
			else:
				options_list.append("-{}".format(option))
				print("-{}".format(option))
	
	# Make sure dumb user doesn't try to override the input filename			
	if "-in:file:s" in options_list:
		bad_file_loc = options_list.index("-in:file:s")+1
		if isinstance(options_list[bad_file_loc], list):
			options_list=options_list[0:bad_file_loc]+options_list[bad_file_loc+1:-1]
		options_list.remove("-in:file:s")
		notify().warn("Flag -in:file:s and associated value(s) will be ignored")

	# Will need to add some code here for dealing with passing native structures 

	# Make sure the necessary options exist, and add them if they don't. These include -pep_refine, -nstruct, -ex1, -ex2aro
	if "-database" not in options_list:
		options_list.append("-database")
		options_list.append(["{}/database".format(ROSETTA_PATH)])
	if "-pep_refine" not in options_list:
		options_list.append("-pep_refine")
	if "-nstruct" not in options_list:
		options_list.append("-nstruct")
		options_list.append(["{}".format(250)]) #Default structures per run
	if "-ex1" not in options_list:
		options_list.append("-ex1")
	if "-ex2aro" not in options_list:
		options_list.append("-ex2aro")

	# First thing we do is open the fasta files or peptide squence files and determine the number of sequences present:
	peptide_list_fh = open(peptide_list, "r")
	records = peptide_list_fh.read().splitlines()
	record_sequences=[x for x in records if ">" not in x]
	record_names=[x[1:] for x in records if ">" in x] # This should only populate if a fasta file is passed
	peptide_list_fh.close()

	# Some more error checking for bad input:
	if len(record_names)>0 and len(record_names) != len(record_sequences):
		notify().warn("{} sequences but {} sequence IDs! --threadprep takes either a .fasta file with a list of sequence and sequence IDs, or a list of peptide sequences (one per line)".format(len(record_sequences), len(record_names)))
	
	# Now we assign sequence names if we got a peptide sequences list rather than a fasta file:
	if len(record_names)==0:
		print("List of peptide sequences detected. Parsing with arbitrary name designation...")
		count_records=0
		for r in records:
			count_records+=1
			record_names.append("P{}".format(count_records))

	# Obtain rotamers filename
	if params:
		params = os.path.abspath(params)
		params_fh = open(os.path.abspath(params))
		rotamers_fn = os.path.join(os.path.dirname(params), params_fh.readlines()[-1].split(" ")[1])
		params_fh.close()

	# Time to iterate through each sequence and produce the folder containing the prepacked, input file, slurm file, options file, and output folder.
	for sequence, name in zip(record_sequences, record_names):
		
		options_list_tmp = options_list[:]
		print("\nNow processing:")
		notify().notice(f"Name: {name}")
		notify().notice(f"Sequence: {sequence}")

		# Wait just one minute...did we forget our params file?
		has_NCAA=False
		if "X" in sequence:
			if not params:
				notify().warn("Sequence {} contains placeholder residue 'X' for a NCAA, but no params file passed. Skipping...\033[0m".format(name))
				continue
			
			if not Path(os.path.abspath(rotamers_fn)).is_file():
				notify().warn("Rotamers file {} associated with provided params file {} not located. Sequence {} will be skipped...\033[0m".format(os.path.abspath(rotamers_fn), os.path.abspath(params), name))
				continue

			else:
				options_list_tmp.append("-in:file:extra_res_fa")
				options_list_tmp.append(["{}".format(os.path.basename(params))])
				has_NCAA=True
		
		# Ok, phew, glad we have it. Now let's move on.

		# Now we create our folder, move into the folder, write our fasta file, and pass that info to thread_template
		# Here is an overview of the file structure for the production run:
		# <Allele Name> (parent directory)
		# 	<output> 	(silent files go here)
		# 	<batch 1
		# 		<peptide 1>
		# 			peptide1.slurm
		# 			peptide1.options
		# 			peptide1.fasta
		# 			peptide1_input.pdb
		# 		<peptide 2>
		# 			...
		# 	...
		# 	<batch N>
		new_dir=os.path.join(parent_dir, "{}".format(name))
		os.mkdir(new_dir)
		os.chdir(new_dir)
		
		# Write our temporary fasta file
		tmp_fasta="{}.fasta".format(name)
		print(f"Writing fasta file to: {tmp_fasta}")
		SeqIO.write(SeqRecord(Seq(sequence),id="{}".format(name)), tmp_fasta, "fasta")

		# Call thread_template
		if has_NCAA:
			input_filename=thread_template(tmp_fasta, mhcdb, ROSETTA_PATH, user_defined_receptor=user_defined_receptor, params=params, ignore_perfect_match=ignore_perfect_match,find_worst_template=find_worst_template)
		else:
			input_filename=thread_template(tmp_fasta, mhcdb, ROSETTA_PATH, user_defined_receptor=user_defined_receptor,ignore_perfect_match=ignore_perfect_match,find_worst_template=find_worst_template)
		
		if not input_filename:
			print(f"❌ DEBUG: thread_template failed for {name} - Check XML and Rosetta logs")
			notify().error(f"Aborting {name}: {sequence}")
			os.chdir(parent_dir)
			continue

		# Make our slurm and options files
		### Comment out slurm file
		#slurm_fh = open("{}.slurm".format(name),"w")
		#slurm_fh.write("#!/bin/bash\n")
		#for key, value in slurm_options.items():
		#	slurm_fh.write("#SBATCH --{}={}\n".format(key,value))

		# allele_name=allele[0]+allele[2:4]+allele[5:]
		allele_name=allele
		# 
		# if has_NCAA:
		# 	K_KIS="KIS"
		# else:
		# 	K_KIS="K"python IEDBTestPipeline.py /path/to/folder

		### Comment out slurm file
		#slurm_fh.write("\nmodule load GCC/6.4.0-2.28\n")
		#slurm_fh.close()

		# Add path for out input threaded model
		options_list_tmp.append("-in:file:s")
		options_list_tmp.append(["{}/{}".format(name,os.path.basename(input_filename))])

		# options_list_tmp.append("-native")
		
		# Iterate through options for our options file and write them in 
		#options_fh = open("{}.options".format(name),"w")
		#for x in options_list_tmp:
		#	if isinstance(x, list):
		#		for y in x:
		#			options_fh.write(" {}".format(y))
		#		options_fh.write("\n")
		#	else:
		#		options_fh.write("\n{}".format(x))
		#options_fh.close()

		# Move our params file and associated rotamers file into the folder if it exists
		if params:
			shutil.copyfile(os.path.abspath(params), os.path.join(new_dir, os.path.basename(params)))
			shutil.copyfile(rotamers_fn, os.path.join(new_dir, os.path.basename(rotamers_fn)))

		# Finally we move up one level to our original directory and repeat the process for every record
		os.chdir(parent_dir)

	return

##### Safe_thread_all to prevent crashes when errors occur
def safe_thread_all(d, mhcdb, rosetta, receptor, **kwargs):
    try:
        return thread_all(d, mhcdb, rosetta, receptor, **kwargs)
    except Exception as e:
        print(f"Error processing batch with kwargs: {kwargs}. Error: {e}")
        return None

##==MAIN BODY OF EXECUTION==##
# Dependencies from standard python library
import argparse 		
import sys
import os
import glob
import multiprocessing
import math
from pathlib import Path
from zipfile import ZipFile
import shutil
import re
import xml.etree.ElementTree as ET #import ElementTree to handle xml file creation
import subprocess
import warnings
from Bio import BiopythonDeprecationWarning
warnings.filterwarnings("ignore", category=BiopythonDeprecationWarning)

# Dependencies from other libraries
import pandas as pd
import numpy as np
import requests
## Biopython
import Bio
import sys
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Align import PairwiseAligner
from Bio import AlignIO
from Bio.Align import substitution_matrices
from Bio import PDB
from Bio.PDB import PDBParser
from Bio.PDB import PDBIO

# Custom dependencies
from formats import notify
from formats import progressBar
from HLA_db import MHCdatabase


# Parse input arguments
parser = argparse.ArgumentParser(description='IEDBTestPipeline.py', usage=help_msg())
# Arguments to initiate pipeline:
parser.add_argument('--IEDBquery', nargs='*', default=['all'], help='Initiates pipeline by querying a local copy of the IEDB database, extracting all epitopes belonging to a specified allele and returning a curated list for manual review (unless --skipreview is passed). Followed by one or more alleles in the format "A*01:01", a filename with one allele per line (preceded by "@", for example @hla_list.txt"), or "all" to get affinity binding data for all alleles in the database. Additional arguments include: "skip", to skip the query and proceed with processing with a fasta file; "ncaa" to include epitopes with NCAA in their sequences')
parser.add_argument('--assay',nargs='*',default=['qualitative_binding', 'dissociation_constant_KD_(~EC50)', 'ligand_presentation', 'half_life', '3D_structure', 'half_maximal_inhibitory_concentration_(IC50)', 'dissociation_constant_KD_(~IC50)', '50%_dissociation_temperature', 'dissociation_constant_KD', 'half_maximal_effective_concentration_(EC50)', 'off_rate'], help='Optional argument to specify assay values to retrieve. Can pass "help" to list all assay values available. IMPORTANT: list values with "_" character in place of spaces. For example: dissociation_constant_KD_(~IC50)')

# Alternative argument to initiate pipeline with only a fasta file, or a fasta file+curated sequence file generated by --IEDBquery:
parser.add_argument('--buildFasta', nargs=2, help='Followed by path to .fasta and curated sequences in .csv file. May pass False or 0 for second positional argument if you just want to run the pipeline with a pre-made .fasta file')

# Mandatory arguments for pipeline execution:
parser.add_argument('--setAllele', nargs=1, help='Specify the MHC allele that will serve as the receptor')
parser.add_argument('--batchSize', nargs=1, type=int, help='Number of sequences per batch for production run. If a batch size is small, then multiprocessing will attempt to produce input files using a larger number of CPUs simultaneously. Smallest value is 1.')

# Optional arguments for pipeline execution:python IEDBTestPipeline.py /path/to/folder
parser.add_argument('--skipReview', action='store_true', help='Designate that flagged data should be disregarded. Use in conjunction with other flags to proceed down the pipeline without interruption')
parser.add_argument('--params', nargs='*', help='Followed by path to params file and optional position to make an NCAA substitution')
parser.add_argument('--rosetta', nargs=1, default=[os.environ.get("PEPBIND3D_ROSETTA", "/dors/meilerlab/apps/rosetta/rosetta-3.14/main")], help='Optional flag for defining path to rosetta/main. Default is /dors/meilerlab/apps/rosetta/rosetta-3.14/main')
parser.add_argument('--mhcdatabase', nargs=1, help='Followed by a location to the MHC database (default is /home/<user>/Data/MHC_database')
parser.add_argument('--receptor', nargs=1, default=[None], help='Optional flag to define a receptor for --threadprep')
parser.add_argument('--slurm', nargs='*', help='Optional flag to make slurm file for flexpepdock refinment production run. Takes in an arbitrary number of arguments that correspond to #SBATCH option and value pairs, delimited as option=value')
parser.add_argument('--options', nargs='*', help='Optional flag to make options file for flexpepdock refinement production run. Takes in an arbitrary number of arguments that correspond to command-line options for flexpepdock refinement. Command line arguments with assigned values are designated with a "=" character. For example: input_file=my.file is translated to -input_file my.file. Multiple values for a single argument can be set with values separated by subsequent "=" characters. For example: set_values=val1=val2=val3 is parsed to -set_values val1 val2 val3')
parser.add_argument('--ignore_epitope_match', action="store_true",help="Optional flag to ignore sequence matches when identifying a template")
parser.add_argument('--find_worst_template',action="store_true",help="Optional flag to locate the worst template by sequence (rather than best)")

# Flag for postprocessing of silent files and correlated with affinity data generated during pipeline initiation.
parser.add_argument('--post', nargs='*', help='Optional flag to initiate postprocessing. Pass "build" followed by a directory to silent files to create a scorefile; may optionally pass an integer number of models to retrieve after sorting by score. Pass "affinity" followed by filtered IEDB .csv, scorefile, and (optional) cleaned flagged IEDB .csv to generate statistics on model performance for predicting epitope binding affinity from score alone. Pass "stat", "stats", or "statistics" and a scorefile with "Epitope_ID" and "Quantitative_Measurement" columns to produced binding affinity statistics only')

# Argument parser for running on cluster
parser.add_argument("--threads", type=int, default=1, help="Number of threads to use for multiprocessing (should be 1 per job in the array).")
parser.add_argument("--slurm_setup", action="store_true", help="Only create batches and exit (for SLURM setup)")

args = parser.parse_args()
#print(f"DEBUG: Parsed arguments in IEDBTestPipeline -> {args}")

if args.mhcdatabase:
	mhcdb=MHCdatabase(location=args.mhcdatabase[0])
else:
	mhcdb=MHCdatabase()

if args.slurm_setup and args.buildFasta:
    # Automatically detect allele based on the folder name
    detected_allele = get_allele_from_folder(args.buildFasta[0])

    # Automatically set the allele for the pipeline
    args.setAllele = [detected_allele]
    print(f"Automatically detected allele: {detected_allele}")

# Check for postprocessing request
if args.post:
	if "build" in args.post and len(args.post)>1:
		if os.path.isdir(args.post[1]):
			if len(args.post)>2 and args.post[2].isdigit():
				scname=build_scorefile(args.post[1],get_top_mod=int(args.post[2]))
			else:
				scname=build_scorefile(args.post[1])
		else:
			notify().error(f"Directory {args.post[1]} does not exist!")
			sys.exit()
		notify().notice(f"Scorefile built and saved to {scname}")
		sys.exit()
	if "affinity" in args.post:
		if len(args.post)<3:
			parser.print_help()
			notify().error(f"{len(args.post)-1} arguments passed with affinity, correct usage is --post affinity <IEDB filtered> <scorefile> <IEDB flagged>")
		elif len(args.post)==3:
			postprocessing_affinity(args.post[1], args.post[2])
		else:
			postprocessing_affinity(args.post[1], args.post[2], args.post[3])
	elif "stat" in args.post:
		if len(args.post)<2 or not os.path.isfile(args.post[1]):
			notify().error(f"No valid scorefile detected")
		else:
			stats_from_scorefile(args.post[1])
	sys.exit()

# Initiate pipeline with IEDB query file cleaning, fasta rebuilding, or premade fasta
if "skip" not in args.IEDBquery:
	print("Proceeding with IEDB query...")
	if args.assay[0]=='help':
		sys.exit("===IEDB MHC binding assay values available:===\n{}".format('\n'.join(parser.get_default('assay'))))
	else:
		# Brief error check to make sure all requested assay values are valid:
		test=list(set(args.assay)-set(parser.get_default('assay')))
		if len(test)>0:
			notify().warn(f"User requested assay values {', '.join(test)} not available and will be ignored")
			print("===IEDB MHC binding assay values available:===\n{}".format('\n'.join(parser.get_default('assay'))))
		fasta_fn=get_peplist(args.IEDBquery[0],assay_values=args.assay) #041725 edit

	if fasta_fn==None:
		raise RuntimeError("Terminating pipeline")
	if not args.skipReview:
		sys.exit(notify().notice('Exiting for manual review. Pass --buildFasta with .fasta file and curated sequences to resume'))
elif args.buildFasta:
	print(f"Rebuilding fasta from {args.buildFasta[0]} and {args.buildFasta[1]}")
	fasta_fn=fasta_rebuild(args.buildFasta[0],args.buildFasta[1])
	print(f"fasta_fn after rebuilding: {fasta_fn}")
else:
	sys.exit(notify().error('Must supply IEDB database query file with --IEDBquery or pass the --buildFasta after manual sequence curation to proceed with pipeline'))

# Make sure the user specified an allele that exists
if args.setAllele:
	chk = mhcdb.set_allele(args.setAllele[0])
	print(f"Setting allele to {args.setAllele[0]}")
	if not chk:
		sys.exit()
	print(f"MHC allele set to {mhcdb.allele}")
else:
	sys.exit(notify().error("Must supply valid allele with --setAllele flag!"))

# Add NCAA if --params is passed (with optional position to replace in sequence, indexed from 1)
add_params=False
if args.params:
	if len(args.params)>1:
		add_NCAA(fasta_fn, args.params[0], position=args.params[1])
	else:
		add_NCAA(fasta_fn, args.params[0])
	if args.params[0]:
		add_params=args.params[0]
	else:
		print("WARNING: args.params[0] is empty. Skipping NCAA handling.")

# ======== Batch the FASTA file ========
batchlist = make_batch(fasta_fn, args.batchSize[0] if args.batchSize else None)

# Modify the --batch_index argument to be optional if --slurm_setup is passed
#if not args.slurm_setup:
#    parser.add_argument("--batch_index", type=int, required=True, help="Index of the batch folder to process.")
#else:
#    parser.add_argument("--batch_index", type=int, required=False, help="Index of the batch folder to process.")

# ======== Slurm set up mode ========
#if args.slurm_setup:
#	create_batch_list(base_dir)
#	sys.exit("Batch list generated and saved to batch_list.txt. You can now submit SLURM jobs.")


# ======== Slurm job array mode (per batch execution) ========
#if args.batch_index is not None:
#	if not os.path.exists("batch_list.txt"):
#		sys.exit("Error: batch_list.txt not found. Run with --slurm_setup first.")

	# Read the batch list from the generated file
#	with open("batch_list.txt") as f:
#		batchlist = [line.strip() for line in f.readlines()]

#	if args.batch_index < 0 or args.batch_index >= len(batchlist):
#		sys.exit(f"Error: Invalid batch_index {args.batch_index}.")

#	batch_folder = batchlist[args.batch_index]
#	print(f"Processing batch folder {batch_folder} with {args.threads} threads...")

#	pool = multiprocessing.Pool(args.threads)
#	pool.apply_async(safe_thread_all,(batch_folder, mhcdb, args.rosetta[0], args.receptor[0]), dict(params=add_params, for_production=[args.slurm, args.options], ignore_perfect_match=args.ignore_epitope_match, find_worst_template=args.find_worst_template))
#	pool.close()
#	pool.join()
#	print("Batch folder processing complete.")
#	sys.exit()

# ======== Default mode: Process all batches locally ========
batchlist = make_batch(fasta_fn, args.batchSize[0] if args.batchSize else None)
print(f"Starting multiprocessing with {args.threads} threads across {len(batchlist)} batches...")
pool = multiprocessing.Pool(args.threads)

for d in batchlist:
	print(f"Threading peptides in {os.path.basename(d)}")
	pool.apply_async(safe_thread_all, (d, mhcdb, args.rosetta[0], args.receptor[0]), dict(params=add_params, for_production=[args.slurm, args.options], ignore_perfect_match=args.ignore_epitope_match, find_worst_template=args.find_worst_template))

pool.close()
pool.join()
notify().notice("All batches processed.")
